server:
  port: 8765

spring:
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: taskmanager-ms
          uri: http://localhost:8087/
          predicates:
            - Path=/tasks/**
        - id: message-service-ms
          uri: http://localhost:8088/
          predicates:
            - Path=/messages/**
        - id: user-service-ms
          uri: http://localhost:8085/
          predicates:
            - Path=/users/**
        - id: adds-service-ms
          uri: http://localhost:8084/
          predicates:
            - Path=/adds/**
