server:
  port: 8080
spring:
  output.ansi.enabled: ALWAYS
api:
  host: "http://localhost"
  serverPort: 8080
  gatewayPort: 8765
  urlApiTasks: "/tasks"
  urlApiMessages: "/messages"
  urlApiUsers: "/users"
  
